# Generated by Django 4.2 on 2023-07-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_last_message_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='isreaded',
            field=models.BooleanField(default=False),
        ),
    ]
