# Generated by Django 4.2 on 2023-04-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='visit_type',
            field=models.CharField(choices=[('new', 'New'), ('revisit', 'Re-Visit')], default='new', max_length=9),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duration',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
