# Generated by Django 4.2 on 2023-04-22 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_drprofile_affiliated_with_and_more'),
        ('patient', '0002_alter_patientprofile_profile_image'),
        ('appointment', '0003_appointment_visit_type_alter_appointment_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='doctor.drprofile'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to='patient.patientprofile'),
        ),
    ]
