# Generated by Django 4.2 on 2023-07-02 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0026_alter_apply_doctor_alter_apply_student'),
        ('appointment', '0006_alter_appointment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hs_appointments', to='hospital.hospitalprofile'),
        ),
    ]
