# Generated by Django 4.2 on 2023-07-30 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_appointment_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='scheduled_time',
        ),
    ]
