# Generated by Django 4.2 on 2023-06-05 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Only alphabetic characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=35, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Only alphabetic characters are allowed.')]),
        ),
    ]
