# Generated by Django 4.2 on 2023-04-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='profile_image',
            field=models.ImageField(default='images/default.jpg', upload_to='patient_profile_images/'),
        ),
    ]
