# Generated by Django 4.2 on 2023-05-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_rename_profile_image_patientprofile_profpic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='profemail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
