# Generated by Django 4.2 on 2023-06-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patientprofile_profemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='language',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
    ]
