# Generated by Django 4.2 on 2023-06-04 08:14

import accounts.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_patientprofile_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='websitelink',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='youtubelink',
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='phone',
            field=accounts.utils.MobileNumberField(blank=True, max_length=20, null=True),
        ),
    ]
