# Generated by Django 4.2 on 2023-05-20 18:20

import accounts.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(default='images/default.jpg', upload_to='student_profile_images/')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('date_of_birth', models.DateField(null=True)),
                ('phone', accounts.utils.MobileNumberField(max_length=20, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('profemail', models.EmailField(blank=True, max_length=254, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('biography', models.CharField(blank=True, max_length=250, null=True)),
                ('fblink', models.URLField(blank=True, null=True)),
                ('instalink', models.URLField(blank=True, null=True)),
                ('youtubelink', models.URLField(blank=True, null=True)),
                ('websitelink', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.OneToOneField(limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
