# Generated by Django 4.2 on 2023-05-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profpic',
            field=models.ImageField(default='/images/default.jpg', upload_to='student_profile_images'),
        ),
    ]
