# Generated by Django 4.2 on 2023-08-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentprofile_major_workexperience_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='institute',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='position',
            field=models.CharField(blank=True, max_length=2355, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
