# Generated by Django 4.2 on 2023-07-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_remove_follow_unique_followers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('image', models.ImageField(default='images/21.jpg', upload_to='notifications/')),
                ('name', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('read', 'read'), ('unread', 'unread')], default='unread', max_length=20)),
                ('notification_type', models.CharField(choices=[('t_message', 't_message'), ('s_message', 's_message'), ('meeting', 'meeting'), ('class', 'class'), ('assignment', 'assignment'), ('quiz', 'quiz')], default='', max_length=30)),
                ('receiver_id', models.CharField(blank=True, max_length=255, null=True)),
                ('read_by', models.CharField(blank=True, default='[]', max_length=255, null=True)),
                ('chat_id', models.CharField(blank=True, max_length=255, null=True)),
                ('teacher_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('message_type', models.CharField(blank=True, max_length=255, null=True)),
                ('assignment_quiz_meeting_class_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'db_table': 'notifications',
            },
        ),
    ]
