# Generated by Django 4.2 on 2023-07-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.AlterField(
            model_name='notification',
            name='receiver_id',
            field=models.CharField(blank=True, default='[]', max_length=255, null=True),
        ),
    ]
