# Generated by Django 4.2 on 2023-04-10 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0003_alter_hospitalprofile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalprofile',
            name='joined_doctors',
            field=models.ManyToManyField(related_name='joined_doctors', to=settings.AUTH_USER_MODEL),
        ),
    ]
