# Generated by Django 4.2 on 2023-04-10 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0004_hospitalprofile_joined_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofile',
            name='joined_doctors',
            field=models.ManyToManyField(limit_choices_to={'role': 'doctors'}, related_name='joined_doctors', to=settings.AUTH_USER_MODEL),
        ),
    ]
