# Generated by Django 4.2 on 2023-04-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_drprofile_affiliated_with_and_more'),
        ('hospital', '0008_alter_hospitalprofile_joined_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofile',
            name='joined_doctors',
            field=models.ManyToManyField(related_name='joined_doctors', to='doctor.drprofile'),
        ),
    ]
