# Generated by Django 4.2 on 2023-04-23 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_alter_hospitalprofile_joined_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='joined_doctors',
        ),
    ]
