# Generated by Django 4.2 on 2023-04-24 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_hospitalprofile_joined_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hospitalgallery')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='hospital.hospitalprofile')),
            ],
        ),
    ]
