# Generated by Django 4.2 on 2023-04-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
