# Generated by Django 4.2 on 2023-04-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_alter_gallery_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldepartment',
            name='dptphoto',
            field=models.ImageField(default='/images/defaultdepartment.PNG', upload_to='hospitalgallery'),
        ),
    ]
