# Generated by Django 4.2 on 2023-05-09 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_hospitaldepartment_dptphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('srphoto', models.ImageField(default='/images/defaultdepartment.PNG', upload_to='hospitalservices')),
                ('description', models.TextField(null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hospital.hospitalprofile')),
            ],
        ),
    ]
