# Generated by Django 4.2 on 2023-05-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_hospitalservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalservices',
            name='srphoto',
            field=models.ImageField(blank=True, null=True, upload_to='hospitalservices'),
        ),
    ]
