# Generated by Django 4.2 on 2023-05-13 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_drprofile_affiliated_with_and_more'),
        ('hospital', '0016_alter_hospitalservices_srphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliated_doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_from', models.DateField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliated_docotr', to='doctor.drprofile')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to='hospital.hospitalprofile')),
            ],
        ),
    ]
