# Generated by Django 4.2 on 2023-05-13 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_affiliated_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='joined_doctors',
        ),
    ]
