# Generated by Django 4.2 on 2023-05-13 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_remove_hospitalprofile_joined_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliated_doctors',
            name='doctor',
        ),
        migrations.AlterField(
            model_name='affiliated_doctors',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hs', to='hospital.hospitalprofile'),
        ),
    ]
