# Generated by Django 4.2 on 2023-05-23 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_affiliated_doctors_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('position', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('volinteer', 'Volinteer'), ('internship', 'Internship'), ('other', 'Other')], max_length=20)),
                ('workplace', models.CharField(choices=[('onsite', 'Onsite'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=20)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('qualification', models.TextField(blank=True, max_length=255, null=True)),
                ('requirements', models.TextField(max_length=255)),
                ('start_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('end_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='hospital.hospitalprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
