# Generated by Django 4.2 on 2023-06-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_job_delete_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='open_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
