# Generated by Django 4.2 on 2023-07-01 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0019_alter_research_options'),
        ('student', '0003_studentprofile_major_workexperience_education'),
        ('hospital', '0025_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dr_applies', to='doctor.drprofile'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='st_applies', to='student.studentprofile'),
        ),
    ]
