# Generated by Django 4.2 on 2023-07-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0026_alter_apply_doctor_alter_apply_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apply',
            options={'ordering': ['-applied_at']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-published_at']},
        ),
    ]
