# Generated by Django 4.2 on 2023-07-17 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0021_alter_researchapply_student'),
        ('student', '0003_studentprofile_major_workexperience_education'),
        ('hospital', '0027_alter_apply_options_alter_job_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliated_doctors',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliated_hs', to='student.studentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='affiliated_doctors',
            unique_together={('hospital', 'doctor')},
        ),
    ]
