# Generated by Django 4.2 on 2023-07-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0028_affiliated_doctors_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliated_doctors',
            name='positoin',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
