# Generated by Django 4.2 on 2023-07-17 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0029_affiliated_doctors_positoin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliated_doctors',
            old_name='positoin',
            new_name='position',
        ),
    ]
