# Generated by Django 4.2 on 2023-07-17 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0021_alter_researchapply_student'),
        ('student', '0003_studentprofile_major_workexperience_education'),
        ('hospital', '0031_alter_affiliated_doctors_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='affiliated_doctors',
            unique_together={('student', 'position', 'hospital', 'doctor')},
        ),
    ]
