# Generated by Django 4.2 on 2023-04-05 03:50

import accounts.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('start_date', models.DateField(blank=True, default=None, null=True)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='DrProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('profpic', models.ImageField(default='/images/default.jpg', upload_to='dr_profile_pics')),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=1, max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('work_address', models.CharField(blank=True, max_length=100, null=True)),
                ('Consultancy_Charge', models.PositiveIntegerField(null=True)),
                ('phone', accounts.utils.MobileNumberField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliated_with', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'role': 'hospital'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliated_doctors', to=settings.AUTH_USER_MODEL)),
                ('interested', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'role': 'hospital'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interested_doctors', to=settings.AUTH_USER_MODEL)),
                ('name', models.OneToOneField(limit_choices_to={'is_active': True, 'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
