# Generated by Django 4.2 on 2023-04-05 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drprofile',
            name='affiliated_with',
        ),
        migrations.RemoveField(
            model_name='drprofile',
            name='interested',
        ),
    ]
