# Generated by Django 4.2 on 2023-05-17 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_drprofile_affiliated_with_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drprofile',
            name='qualifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.qualification'),
        ),
        migrations.AddField(
            model_name='drprofile',
            name='specialities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.speciality'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='institute',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='name',
            field=models.CharField(default='mbbs', max_length=55),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='name',
            field=models.CharField(default='cadio', max_length=55),
        ),
    ]
