# Generated by Django 4.2 on 2023-05-17 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_drprofile_qualifications_drprofile_specialities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drprofile',
            name='qualifications',
        ),
    ]
