# Generated by Django 4.2 on 2023-05-17 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_remove_drprofile_qualifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='name',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='start_date',
        ),
    ]
