# Generated by Django 4.2 on 2023-05-17 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_remove_qualification_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drprofile',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='drprofile',
            name='qualifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.qualification'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='institute',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='name',
            field=models.CharField(default='mbbs', max_length=55),
        ),
        migrations.AddField(
            model_name='qualification',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='name',
            field=models.CharField(default='cardio', max_length=55),
        ),
    ]
