# Generated by Django 4.2 on 2023-05-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_remove_drprofile_is_deleted_drprofile_qualifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drprofile',
            name='profemail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
