# Generated by Django 4.2 on 2023-05-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_remove_drprofile_qualifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drprofile',
            name='biography',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
