# Generated by Django 4.2 on 2023-05-18 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_drprofile_linkedin_drprofile_twitter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='drprofile',
            name='specialities',
        ),
        migrations.RemoveField(
            model_name='drprofile',
            name='workExperience',
        ),
        migrations.AddField(
            model_name='education',
            name='dr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.drprofile'),
        ),
        migrations.AddField(
            model_name='speciality',
            name='dr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.drprofile'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='dr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.drprofile'),
        ),
    ]
