# Generated by Django 4.2 on 2023-05-18 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_remove_drprofile_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='dr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialities', to='doctor.drprofile'),
        ),
    ]
