# Generated by Django 4.2 on 2023-05-18 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_alter_speciality_dr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='dr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='doctor.drprofile'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='dr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_experience', to='doctor.drprofile'),
        ),
    ]
