# Generated by Django 4.2 on 2023-05-20 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_alter_education_dr_alter_workexperience_dr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='dr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='doctor.drprofile'),
        ),
    ]
