# Generated by Django 4.2 on 2023-06-27 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0018_research'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='research',
            options={'ordering': ['-posted_at']},
        ),
    ]
