# Generated by Django 4.2 on 2023-07-02 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentprofile_major_workexperience_education'),
        ('doctor', '0020_researchapply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchapply',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_application', to='student.studentprofile'),
        ),
    ]
