# Generated by Django 4.2 on 2023-07-29 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0021_alter_researchapply_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchapply',
            options={'ordering': ['-applied_at']},
        ),
    ]
