# Generated by Django 4.2 on 2023-07-29 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0022_alter_researchapply_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='is_active',
        ),
    ]
