# Generated by Django 4.2 on 2023-07-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0023_remove_research_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='drprofile',
            name='max_appointment_time',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='drprofile',
            name='working_hours_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drprofile',
            name='working_hours_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
